cookie:
  expiry_days: 30
  key: g7iyDFDNFoSad8ZSlZvZENkFW7jzAN72WDhtLCiEGDw=
  name: loginCookie
credentials:
  usernames:
    dbaq:
      email: dnnbaq@gmail.com
      logged_in: false
      name: Tommy dbaq
      password: $2b$12$DAb48.1IChJyUjoQS2ZtG.6QQZ6zGlIIZFba9z6t.nW/28RNKfxnS
    jsmith:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: $2b$12$vyLNWaUbYnWNBXbGZCtx/O7fjzhAuQmWek/HzdafO3yMjE1JR6HV6
    ltyag:
      email: ltanyag@gmail.com
      logged_in: false
      name: Tommy Tanyag
      password: $2b$12$5L1c9qscCMGZ.f7cq0He9uf8fIYCerZ0SnlppVl4.KNs3alj.2yti
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$4whCeHskiXgE4gPVFDeaGeJIEW.AsWZEWOslkqP.cmbEToNOlvFEa
    sid:
      email: sid77449@gmail.com
      logged_in: false
      name: sid
      password: $2b$12$hY1MHTAuS8V2ooEb7XsWUujT03r9mobIaTB9kLrMVxKjTnTtjlfTy
preauthorized:
  emails:
  - melsby@gmail.com
